openapi: 3.0.3
info:
  title: Starwars
  description: |-
    This is to grab starwars characters
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://swapi.dev/api
paths:
  /people/{id}:
    get:
      summary: Find character by ID
      description: Returns a single character
      operationId: getCharacterById
      parameters:
        - name: id
          in: path
          description: ID of character to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
        "400":
          description: Invalid ID supplied
        "404":
          description: Character not found
components:
  schemas:
    Character:
      required:
        - name
        - height
        - mass
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
        height:
          type: string
        mass:
          type: string
